-- MySQL Script generated by MySQL Workbench
-- Thu Sep 23 16:23:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Cliente_id` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Cedula` INT NOT NULL,
  PRIMARY KEY (`Cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puestos` (
  `Puesto_asignado_id` INT NOT NULL,
  `Disponibilidad` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Puesto_asignado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `Vehiculo_id` INT NOT NULL,
  `Fecha_hora_de_ingreso` DATETIME NOT NULL,
  `Fecha_hora_de_salida` DATETIME NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Tipo_vehiculo` VARCHAR(45) NOT NULL,
  `Puesto_asignado_id` VARCHAR(45) NOT NULL,
  `Cliente_Cliente_id` INT NOT NULL,
  `Puestos_Puesto_asignado_id` INT NOT NULL,
  PRIMARY KEY (`Vehiculo_id`, `Cliente_Cliente_id`, `Puestos_Puesto_asignado_id`),
  INDEX `fk_Vehiculo_Cliente1_idx` (`Cliente_Cliente_id` ASC) VISIBLE,
  INDEX `fk_Vehiculo_Puestos1_idx` (`Puestos_Puesto_asignado_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_Cliente1`
    FOREIGN KEY (`Cliente_Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Puestos1`
    FOREIGN KEY (`Puestos_Puesto_asignado_id`)
    REFERENCES `mydb`.`Puestos` (`Puesto_asignado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Usuario_id` INT NOT NULL,
  `Nickname` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaccion` (
  `Transaccion_id` INT NOT NULL,
  `Monto_total` INT NOT NULL,
  `Impuestos` INT NOT NULL,
  `Medio_de_pago` VARCHAR(45) NOT NULL,
  `Dinero_ingresado` INT NOT NULL,
  `Cambio` INT NOT NULL,
  `Cliente_Cliente_id` INT NOT NULL,
  `Vehiculo_Vehiculo_id` INT NOT NULL,
  `Vehiculo_Cliente_Cliente_id` INT NOT NULL,
  `Usuario_Usuario_id` INT NOT NULL,
  PRIMARY KEY (`Transaccion_id`, `Cliente_Cliente_id`, `Vehiculo_Vehiculo_id`, `Vehiculo_Cliente_Cliente_id`, `Usuario_Usuario_id`),
  INDEX `fk_Transaccion_Cliente1_idx` (`Cliente_Cliente_id` ASC) VISIBLE,
  INDEX `fk_Transaccion_Vehiculo1_idx` (`Vehiculo_Vehiculo_id` ASC, `Vehiculo_Cliente_Cliente_id` ASC) VISIBLE,
  INDEX `fk_Transaccion_Usuario1_idx` (`Usuario_Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transaccion_Cliente1`
    FOREIGN KEY (`Cliente_Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_Vehiculo1`
    FOREIGN KEY (`Vehiculo_Vehiculo_id` , `Vehiculo_Cliente_Cliente_id`)
    REFERENCES `mydb`.`Vehiculo` (`Vehiculo_id` , `Cliente_Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_Usuario1`
    FOREIGN KEY (`Usuario_Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
